### ISSUE TITLE
Elevation type causes null response to Metar request.

### ISSUE THREAD

**Issue by githubuser212** [nathfn/Check-WX-METAR-TAF-API-C-Wrapper#1]
Amazing work! This is a fantastic wrapper. thanks for sharing.

Hit one issue:

Depending on the day and airport, the JsonConvert.DeserializeObject<Metar> results in a null response to the checkWxServices.Metars.SingleDecoded("ICAO") call.

In the Elevation.cs  feet is declared as an "int" type.  However, the response from the Weather service responds with a double ""elevation": {    "feet": 203.41,    "meters": 62  },".   This triggers the try catch during the JSON call and returns a null record.

**Comment by nathfn** [comment]
Thanks @githubuser212! I fixed the issue and published the change to the repository just now :) Happy New Year!
